baseURL = 'https://alfi-lib.github.io'
enableGitInfo = true

defaultContentLanguageInSubdir = true
disableDefaultLanguageRedirect = true
[languages]
[languages.en]
	contentDir = 'content/en'
	languageCode = 'en'
	languageName = 'English'
	title = 'ALFI Library'
	weight = 1
[languages.ru]
	contentDir = 'content/ru'
	languageCode = 'ru'
	languageName = 'Русский'
	title = 'Библиотека ALFI'
	weight = 2

[markup]
[markup.goldmark.renderer]
	unsafe = true
[markup.goldmark.extensions]
[markup.goldmark.extensions.passthrough]
	enable = true
	[markup.goldmark.extensions.passthrough.delimiters]
		block = [['$$', '$$'], ['\[', '\]']]
		inline = [['$', '$'], ['\(', '\)']]
[markup.tableOfContents]
	startLevel = 1
	endLevel = 4

[privacy]
[privacy.disqus]
	disable = true
[privacy.googleAnalytics]
	disable = true
[privacy.instagram]
	disable = true
[privacy.vimeo]
	disable = true
[privacy.x]
	disable = true
[privacy.youtube]
	disable = true

[module]
[[module.imports]]
	path = 'github.com/pasabanov/hugo-book'

[params]
	BookTheme = 'light'
	BookToC = true
	BookSection = 'docs'
	BookRepo = 'https://github.com/ALFI-lib/alfi-lib.github.io'
	BookEditPath = 'edit/main'
	BookDateFormat = 'January 2, 2006'
	BookSearch = true
	BookGlobalKatex = true
	BookPortableLinks = true
	BookServiceWorker = true
	BookTranslatedOnly = true